SJ-2968 exclude io.netty of 3 version from ES transport library to try to fix java.lang.NoSuchMethodError that occurs during the process of creating ES service (use a word "try" because it works in local mode and it doesn't work in docker)